#!/usr/bin/env python3
import argparse
import ngs_ftp_uploader
parser = argparse.ArgumentParser(
    usage = '%(prog)s [options] <in.tar.gz> <server:/foo/bar/out.zip>')

parser.add_argument('--password', help='Password. If not given, a random password is generated')
parser.add_argument('--version', action='version', version=ngs_ftp_uploader.__version__)
parser.add_argument('infile', help='Name of input file')
parser.add_argument('outfile', help='Name of output zip file')

options = parser.parse_args()


encrypter = ngs_ftp_uploader.file_encrypter.FileEncrypter(options.infile, options.outfile, password=options.password)
encrypter.run()